### ISSUE TITLE
GitHub Pagesで公開してみる

### ISSUE THREAD

**Issue by taisukef** [code4fukui/htmlprac#1]
![image](https://user-images.githubusercontent.com/1715217/140878209-0f54e64b-870c-4f3e-b625-3c2aa4458da6.png)
https://github.com/code4fukui/htmlprac/settings/pages
と設定すると、このアドレスでグローバル公開される
https://code4fukui.github.io/htmlprac/htmlprac.html

**Comment by yrm006** [comment]
お、Pages公開されてる！
thx！

**Comment by yrm006** [comment]
よりシンプルにするため、アップロード機能削除、htmlprac.html -> index.html に改名。

**Comment by ghost** [comment]
Reopen

**Comment by ghost** [comment]
#5

**Comment by ghost** [comment]
> よりシンプルにするため、アップロード機能削除、htmlprac.html -> index.html に改名。
> 
> https://code4fukui.github.io/htmlprac/
殺すよ
