### ISSUE TITLE
パラメータでソースを取り込んで表示できると便利そう

### ISSUE THREAD

**Issue by taisukef** [code4fukui/htmlprac#4]
https://code4fukui.github.io/htmlprac/?src=https://code4fukui.github.io/Paper-es/hit-testing.html

と書いて開くと、HTMLをfetchして、デフォルトで設定しておく
簡単に試せて、編集できて楽しい

**Comment by taisukef** [comment]
取り込めるように実装済み

例）
https://code4fukui.github.io/htmlprac/?url=https://code4fukui.github.io/Paper-es/hit-testing.html

**Comment by ghost** [comment]
お前は誰？
